### ISSUE TITLE
The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1

### ISSUE THREAD

**Issue by dsaenztagarro** [mharris717/ember-cli-pagination#159]
```
The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1.
Error: The addon `ember-cli-pagination` requires the npm package `ember-cli` to be above 1.13.0, but you have 2.2.0-beta.1.
    at DependencyVersionChecker.assertAbove (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli-pagination/node_modules/ember-cli-version-checker/index.js:81:18)
    at Class.module.exports.init (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli-pagination/index.js:10:37)
    at new Class (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at /Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/project.js:376:36)
    at Project.eachAddonCommand (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/models/project.js:427:10)
    at module.exports (/Users/dsaenzt/Projects/js_image_client2/node_modules/ember-cli/lib/cli/lookup-command.js:33:13)
```

**Comment by mharris717** [comment]
I just merged a PR this morning that should fix this. I'm going to try and push out a beta version right now. Would you mind being a guinea pig?

**Comment by dsaenztagarro** [comment]
Ok, thank you very much in advance! :+1:

**Comment by mharris717** [comment]
Go for it. Version is 2.2.0-beta.1. Much appreciated.

**Comment by jcope2013** [comment]
any success with new version? that check randomly started acting up

**Comment by mharris717** [comment]
@dsaenztagarro any luck?

**Comment by dsaenztagarro** [comment]
@mharris717 I will give it a try tomorrow morning, as soon as I tested I will provide you with feedback.

Many thanks in advance!!

**Comment by dsaenztagarro** [comment]
Yeyyyy! @mharris717 I just did `npm install` and it worked like a charm.

Thank you very much. :)

**Comment by mharris717** [comment]
Excellent, thanks for the update
