### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by celicoo** [mharris717/ember-cli-pagination#182]
I'm using the exactly docs example:

```javascript
import Ember from 'ember';
import pagedArray from 'ember-cli-pagination/computed/paged-array';

export default Ember.ArrayController.extend({

  // setup our query params
  queryParams: ["page", "perPage"],

  // set default values, can cause problems if left out
  // if value matches default, it won't display in the URL
  page: 1,
  perPage: 10,

  // can be called anything, I've called it pagedContent
  // remember to iterate over pagedContent in your template
  pagedContent: pagedArray('content', {
    pageBinding: "page",
    perPageBinding: "perPage"
  }),

  // // binding the property on the paged array
  // // to a property on the controller
  totalPagesBinding: "pagedContent.totalPages"
});
```

```handlebars
{{#each pagedContent}}
  {{! your app's display logic}}
{{/each}}

{{page-numbers content=pagedContent}}

```

Output:

```bash
ember.debug.js:27773 Error while processing route: dashboard.mappings.index Cannot read property 'slice' of null TypeError: Cannot read property 'slice' of null
    at Class.objsForPage (http://localhost:4200/assets/vendor.js:74871:29)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:75184:31)
    at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:24469:28)
    at Object.get (http://localhost:4200/assets/vendor.js:30121:19)
    at Class._setupArrangedContent (http://localhost:4200/assets/vendor.js:46025:53)
    at Class.init (http://localhost:4200/assets/vendor.js:46181:12)
    at Class.superWrapper [as init] (http://localhost:4200/assets/vendor.js:32478:22)
    at new Class (http://localhost:4200/assets/vendor.js:46323:14)
    at Function.create (http://localhost:4200/assets/vendor.js:46594:14)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:74834:10)
```

**Comment by aalimovs** [comment]
Same here, it's a fresh Ember 2.7 install

Found this https://github.com/mharris717/ember-cli-pagination/issues/116 but no luck

**Comment by jeffrey008** [comment]
Hi guys, what ember version are you using? From ember2.0 onwards, there is no more Ember.ArrayController so I think the readme file is already out of data.

**Comment by celicoo** [comment]
Any update on this? 3 months and the same problem.. --"

**Comment by broerse** [comment]
@celicoo We are working the ember-cli 2.7 update. There will be no more bindings. See https://github.com/mharris717/ember-cli-pagination/issues/186 . I think we are almost there. I will try to update the readme this Sunday. If you have time before that submit a PR  to https://github.com/broerse/ember-cli-pagination/tree/readme2.7.0 or the master branch.

**Comment by broerse** [comment]
@celicoo You can do something like this: https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-posts.js

**Comment by asuraphel** [comment]
Hi @broerse  whats's the status of this issue. BTW I followed your last link and I don't see any diff from the example on README except `ArrayController` has been changed to `Controller`.

**Comment by asuraphel** [comment]
I just saw it again! It's actually changed to `component`. But when will the migration to Ember 2.x be complete?
