### ISSUE TITLE
Stuck at basic installation

### ISSUE THREAD

**Issue by boazin** [mharris717/ember-cli-pagination#73]
I know it's me and not a but but I can't wrap my head around it

Trying the "Remote Paginated API"

My Route:

```javascript
import Ember from 'ember';
import RouteMixin from 'ember-cli-pagination/remote/route-mixin';

export default Ember.Route.extend({
    model: function(params) {
      console.log(this);
      console.log('bla');
      var paged = this.findPaged('session',params);
      console.log(paged);
      return paged;
    }
});
```

I'm getting an error probably somewhere inside findPaged (the last log doesn't happen)
The error:
```
Error while processing route: sessions undefined is not a function TypeError: undefined is not a function
    at __exports__.default.Ember.Route.extend.model (webapp/routes/sessions.js:12:28)
    at apply (http://example.com:8000/static/assets/vendor.js:31555:27)
    at superWrapper [as model] (http://example.com:8000/static/assets/vendor.js:31132:15)
    at EmberObject.extend.deserialize (http://example.com:8000/static/assets/vendor.js:36425:23)
    at applyHook (http://example.com:8000/static/assets/vendor.js:58664:30)
    at Object.HandlerInfo.runSharedModelHook (http://example.com:8000/static/assets/vendor.js:56690:22)
    at Object.subclass.getModel (http://example.com:8000/static/assets/vendor.js:56916:21)
    at http://example.com:8000/static/assets/vendor.js:58538:19
    at tryCatch (http://example.com:8000/static/assets/vendor.js:58992:16)
    at invokeCallback (http://example.com:8000/static/assets/vendor.js:59004:17)
```

And here I'm stuck...

P.S.
JSHint gives me an error - is it related?
```
routes/sessions.js: line 2, col 8, 'RouteMixin' is defined but never used.
```

**Comment by mharris717** [comment]
You didn't add the mixin to the route. 

You want:

```javascript
export default Ember.Route.extend({RouteMixin, {
...
```

Good luck, hope that fixes it. If it does, would appreciate if you can close the issue.

**Comment by Robdel12** [comment]
Also a little tip if you didn't know. Instead of console.logging everything you can throw a `debugger;` in and it'll stop execution right there. You'll have access to all the current vars and can step through things.

Hope that helps a little :)

**Comment by boazin** [comment]
Thanks (for both tips)
