### ISSUE TITLE
Will findPaged methods be affected by store.find deprecations?

### ISSUE THREAD

**Issue by tylergaw** [mharris717/ember-cli-pagination#87]
https://github.com/emberjs/data/issues/2607 deprecates using `store.find` acting like `findAll`. I'm wondering if the `findPaged` methods need to be updated to reflect those changes.

It looks like https://github.com/mharris717/ember-cli-pagination/blob/master/addon/remote/paged-remote-array.js#L76 might be one instance that would need changed? There may be others.

**Comment by lpaluszk** [comment]
Looks like it. This is what I'm getting now.

DEPRECATION: Calling store.find() with a query object is deprecated. Use store.query() instead.
       at find (http://localhost:4200/assets/vendor.js:81792:11)
       at rawFindFromStore (http://localhost:4200/assets/cassidy.js:261:7)
       at fetchContent (http://localhost:4200/assets/cassidy.js:267:7)
       at init (http://localhost:4200/assets/cassidy.js:217:9)
       at Class (http://localhost:4200/assets/vendor.js:45607:9)
       at ClassMixinProps.create (http://localhost:4200/assets/vendor.js:46040:7)
       at findPaged (http://localhost:4200/assets/cassidy.js:764:7)
       at model (http://localhost:4200/assets/cassidy.js:7811:4)
       at deserialize (http://localhost:4200/assets/vendor.js:36270:7)

**Comment by jpaas** [comment]
The deprecation warning for this is coming up now in Ember 1.13

**Comment by mharris717** [comment]
My apologies for taking so long to respond. I believe this should be finally fixed in 0.9.0. 

Thanks for taking the time to submit this issue!
